/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class code_messy_net_RawSocket */

#ifndef _Included_code_messy_net_RawSocket
#define _Included_code_messy_net_RawSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     code_messy_net_RawSocket
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_code_messy_net_RawSocket_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     code_messy_net_RawSocket
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_code_messy_net_RawSocket_nativeOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     code_messy_net_RawSocket
 * Method:    nativeClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_code_messy_net_RawSocket_nativeClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     code_messy_net_RawSocket
 * Method:    nativeRead
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_code_messy_net_RawSocket_nativeRead
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     code_messy_net_RawSocket
 * Method:    nativeWrite
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_code_messy_net_RawSocket_nativeWrite
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     code_messy_net_RawSocket
 * Method:    nativeGetInterfaceNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_code_messy_net_RawSocket_nativeGetInterfaceNames
  (JNIEnv *, jclass);

/*
 * Class:     code_messy_net_RawSocket
 * Method:    nativeGetHardwareAddress
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_code_messy_net_RawSocket_nativeGetHardwareAddress
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
